
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

{/* The following line can be included in your src/index.js or App.js file */ }
import 'bootstrap/dist/css/bootstrap.min.css';
import './globals.css'
import Menu from './Menu'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Menu/>

{/* {true || !!netlifyIdentity.currentUser() && <Menu />} */}
        {children}
      </body>
    </html>
  )
}
